project:
  type: website
  output-dir: docs

website:
  title: "Dilky Felsinger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - projects.qmd
  
  page-footer: 
    background: light
    left: Copyright 2023, Dilky Felsinger
    right: This website is built with [Quarto](https://quarto.org/)

format:
  html:
    theme: 
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    page-layout: full
